#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move

yabai -m config layout bsp

yabai -m config window_gap 10
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10

yabai -m config window_opacity on
yabai -m config active_window_opacity 1
yabai -m config normal_window_opacity 0.95

yabai -m rule --add app="^(AdGuard)$" manage=off;
yabai -m rule --add app="^(Activity Monitor)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Adobe Photoshop)$*" opacity=1.0;
yabai -m rule --add app="^(Adobe Lighroom Classic)$" opacity=1.0;
yabai -m rule --add app="^(Affinity Photo)$" opacity=1.0;
yabai -m rule --add app="^(App Store)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Archive Utility)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Bartender 3)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Bartender 4)$" manage=off opacity=1.0;
yabai -m rule --add app="^(BetterTouchTool)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Bitwarden)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Cascadea)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Calculator)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Calendar)$" manage=off opacity=1.0;
yabai -m rule --add app="^(CleanMyMac X)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Chromium)$" opacity=1.0
yabai -m rule --add app="^(Google Chrome)$" opacity=1.0
yabai -m rule --add app="^(ColorWell)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Contacts)$" manage=off opacity=1.0;
yabai -m rule --add app="^(DeSmuME)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Discord)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Discord)$" title="Discord Updater" manage=off;
yabai -m rule --add app="^(Disk Utility)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Docker Desktop)$" manage=off;
yabai -m rule --add app="^(EPSON XP-540 Series)$" manage=off;
yabai -m rule --add app="^(Finder)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Figma)$" opacity=1.0;
yabai -m rule --add app="^(Firefox)$" opacity=1.0;
yabai -m rule --add app="^(FaceTime)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Font Book)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Flume)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Epic Games Launcher)$" manage=off opacity=1.0;
yabai -m rule --add app="^(extFS for Mac)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Grids)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Hackintool)$" manage=off opacity=1.0;
yabai -m rule --add app="^(HandBrake)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Insomnia)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Karabiner-Elements)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Installer*)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Logic Pro)$" opacity=1.0;
yabai -m rule --add app="^(Mail)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Maps)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Messages)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Microsoft Edge)$" opacity=1.0;
yabai -m rule --add app="^(mGBA)$" manage=off opacity=1.0;
yabai -m rule --add app="^(MTGA)$" manage=off opacity=1.0;
yabai -m rule --add app="^(mpv)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Notes)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Music)$" manage=off opacity=1.0;
yabai -m rule --add app="^(ObinsKit)$" manage=off opacity=1.0
yabai -m rule --add app="^(Paradox Launcher)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Paw)$" manage=off opacity=1.0
yabai -m rule --add app="^(Pixelmator Pro)$" manage=off opacity=1.0
yabai -m rule --add app="^(Photos)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Polarr Photo Editor)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Preview)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Postico)$" manage=off opacity=1.0;
yabai -m rule --add app="^(QuickTime Player)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Radio Silence)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Reminders)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="General" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="Tabs" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="AutoFill" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="Passwords" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="Security" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="Privacy" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="Websites" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="Extensions" manage=off opacity=1.0;
yabai -m rule --add app="^(Safari)$" title="Advanced" manage=off opacity=1.0;
yabai -m rule --add app="^(Simulator)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Spotify)$" manage=off opacity=1.0;
yabai -m rule --add app="^(StarUML)$" opacity=1.0;
yabai -m rule --add app="^(Steam)$" manage=off opacity=1.0;
yabai -m rule --add app="^(System Information)$" manage=off opacity=1.0;
yabai -m rule --add app="^(System Preferences)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Streamlink Twitch GUI)$" opacity=1.0;
yabai -m rule --add app="^(TablePlus)$" manage=off opacity=1.0;
yabai -m rule --add app="^(TextEdit)$" manage=off;
yabai -m rule --add app="^(Topaz Gigapixel AI)$" opacity=1.0;
yabai -m rule --add app="^(Voice Memos)$" manage=off opacity=1.0;
yabai -m rule --add app="^(The Unarchiver)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Transmission)$" manage=off opacity=1.0;
yabai -m rule --add app="^(VK Messenger)$" manage=off opacity=1.0;
yabai -m rule --add app="^(VirtualBox)$" manage=off opacity=1.0;
yabai -m rule --add app="^(VirtualBox VM)$" manage=off opacity=1.0;
yabai -m rule --add app="^(WhatsApp)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Xcode)$" opacity=1.0;
yabai -m rule --add app="^(Yandex)$" opacity=1.0;

# VM
yabai -m rule --add app="^(Parallels Desktop)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Windows 10)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Ubuntu)$" manage=off opacity=1.0;
yabai -m rule --add app="^(Fedora)$" manage=off opacity=1.0;
